---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: sre-dns-latency-exporter
  namespace: openshift-monitoring
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: sre-dns-latency-exporter
  namespace: openshift-monitoring
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: edit
subjects:
- kind: ServiceAccount
  name: sre-dns-latency-exporter
  namespace: openshift-monitoring